name: Deploy dev server

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:     
    - name: deplot via ssh pull
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEV_SERVER_HOST}}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.BUILD_SERVER_SSH_KEY }}
        script: ~/arctos/update.sh
