name: Deploy dev server

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:     
    - name: deploy via ssh pull
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DEV_SERVER_HOST}}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        port: ${{ secrets.DEV_SERVER_SSH_PORT }}
        script: ~/arctos/update.sh
