name: Deploy to xz.ax

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:     
    - name: deplot via ssh pull
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: xz.ax
        username: reid
        key: ${{ secrets.BUILD_SERVER_SSH_KEY }}
        script: /home/reid/arctos/update.sh
