name: Deploy dev server

on:
  push:
    branches: [ dev ]
    paths-ignore:
      - '.github/workflows/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:     
    - name: deploy via ssh pull
      uses: appleboy/ssh-action@v1.0.3
      env: 
        GIT_BRANCH: "origin/dev"
        BUILD_DOCS: "1"
        REPO_ROOT: "$HOME/arctos"
        FRONTEND_SERVER_ROOT: "/var/www/html/"
        DOCS_SERVER_ROOT: "/var/www/docs/"
        CARGO_ENV_FILE: "$HOME/.cargo/env"
      with:
        host: ${{ secrets.DEV_SERVER_HOST}}
        username: ${{ secrets.DEV_SERVER_USER }}
        key: ${{ secrets.DEV_SERVER_SSH_KEY }}
        port: ${{ secrets.DEV_SERVER_SSH_PORT }}
        script: update.sh
        envs: GIT_BRANCH,BUILD_DOCS,REPO_ROOT,FRONTEND_SERVER_ROOT,DOCS_SERVER_ROOT,CARGO_ENV_FILE